ConverterRudraraju/src/ConverterRudraraju/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Data.Entity;

namespace ConverterRudraraju.Models
{
    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        protected override void OnModelCreating(ModelBuilder builder)
        {
            base.OnModelCreating(builder);
            // Customize the ASP.NET Identity model and override the defaults if needed.
            // For example, you can rename the ASP.NET Identity table names and more.
            // Add your customizations after calling base.OnModelCreating(builder);
        }
    }
}

ConverterRudraraju/src/ConverterRudraraju/Models/ApplicationUser.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ConverterRudraraju.Models
{
    // Add profile data for application users by adding properties to the ApplicationUser class
    public class ApplicationUser : IdentityUser
    {
    }
}

ConverterRudraraju/src/ConverterRudraraju/Models/Converter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ConverterRudraraju.Models
{
    public class Converter
    {
        [Display(Name = "ZIP Code")]
        [RegularExpression(@"^\d{5}(?:[-\s]\d{4})?$", ErrorMessage = "Please enter a valid US ZIP code")]
        public int Zipcode { get; set; } = 64468;

        [Required]
        [Range(-12, 120)]
        [Display(Name = "Temperature (F)")]
        public int Temperature_F { get; set; } = 72;
    }
}

ConverterRudraraju/src/ConverterRudraraju/Controllers/Converter/ConverterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ConverterRudraraju.Models;
// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace ConverterRudraraju.Controllers
{
    public class ConverterController : Controller
    {
        public IActionResult Rudraraju()
        {
            ViewData["Title"] = "ConverterApp By Sandeep";
            ViewData["Protip"] = "Sandeep";
            ViewData["Value"] = "";

            Converter converter = new Converter();
            return View(converter);
         }

        
        public IActionResult Convert(Converter converter)
        {
            if (ModelState.IsValid)
            {
                int temp = (int)((converter.Temperature_F - 32) * 5.0 / 9.0);
                ViewData["Title"] = "Converted by Rudraraju";
                ViewData["Result"] = "Temperature in C = " + temp;
                ViewData["Value"] = temp;
            }
            return View("Rudraraju", converter);
        }
    }
}

ConverterRudraraju/src/ConverterRudraraju/Views/Converter/Rudraraju.cshtml
 @{ 
    @model ConverterRudraraju.Models.Converter
     }
    <h2>@ViewData["Title"]</h2>

    <div class="col-xs-12">
        <form asp-controller="Converter" asp-action="Convert" method="post" class="form-horizontal" role="form">

            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Temperature_F"></label>
                <input asp-for="Temperature_F" class="form-control" />
                <span asp-validation-for="Temperature_F" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Convert" class="btn btn-info" />
            </div>

        </form>
    </div>

    <h2>@ViewData["Result"]</h2>

<script>
    if(@ViewData["Value"]<11){
        document.body.style.backgroundImage = "url(http://athletics.elms.edu/images/logos/highres/cool-winter-wallpaper.gif)";

    }
    else if (@ViewData["Value"] >=11 && @ViewData["Value"] <=25){
        document.body.style.backgroundImage = "url(https://www.twolittlefleas.co.uk/wp-content/uploads/2013/09/Curacao-beach.jpg)";
    }
    else{
        document.body.style.backgroundImage = "url(http://www.desktopwallpaperhd.net/wallpapers/5/9/widescreen-weather-wallpaper-hot-desert-background-pictures-53625.jpg)";
    }
</script>

ConverterRudraraju/src/ConverterRudraraju/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>ConverterRudraraju</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
        @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Converter" asp-action="Rudraraju" class="navbar-brand">ConverterRudraraju</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Converter" asp-action="Rudraraju">.</a></li>
                    </ul>
                    @await Html.PartialAsync("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - ConverterRudraraju</p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>